#!/usr/bin/env bash

mkdir -p $HOME/.composer/cache/

test -t 1 && USE_TTY="--tty"

docker run --rm --interactive ${USE_TTY} \
    --user $UID:$UID \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume $PWD:/srv/rest-daemon-example \
    --volume $HOME/.composer:/tmp/.composer \
    --env COMPOSER_HOME=/tmp/.composer \
    free-elephants/rest-daemon-example composer "$@"
